rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails RAILS=3.0.0 DB=postgres
  - GEM=sunspot_rails RAILS=3.1.0 DB=postgres
  - GEM=sunspot_rails RAILS=3.2.0 DB=postgres
  - GEM=sunspot_rails RAILS=4.0.0 DB=postgres

# Limit the size of the matrix by only performing the most common builds
matrix:
  exclude:
    # Not supporting Ruby 2.0 and Rails < 3
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=3.0.0 DB=postgres
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=3.1.0 DB=postgres
    # Not supporting Ruby 1.8.7 and Rails >= 4
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=4.0.0 DB=postgres
  allow_failures:
    # SQLITE fails to load correctly on Travis in Ruby 2.0

script:
  - ci/travis.sh
